API_GATEWAY_ADDR = "http://0.0.0.0:50051"
IMAGE_PATH = "./img"
OUTPUT_PATH = "./output"

client_cert_dir = "./tls/client.pem"
client_key_dir = "./tls/client.key"
server_ca_dir = "./tls/server_ca.pem"
