addr = "0.0.0.0:50051"
ascii_service_addr = "http://0.0.0.0:50056"
blur_service_addr = "http://0.0.0.0:50054"
grayscale_service_addr = "http://0.0.0.0:50052"
pixelate_service_addr = "http://0.0.0.0:50053"
resize_service_addr = "http://0.0.0.0:50057"
